AWSTemplateFormatVersion: "2010-09-09"
Description: Route 53 hosted zone for thearecorder.com

Parameters:
  DomainName:
    Type: String
    Default: thearecorder.com

Resources:
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref DomainName

  # DeliveryMachine inbound email
  MXRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Ref DomainName
      Type: MX
      TTL: 300
      ResourceRecords:
        - "10 mx.deliverymachine.net"

  # DeliveryMachine domain verification
  DMVerifyRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Sub "_dm-verify.${DomainName}"
      Type: TXT
      TTL: 300
      ResourceRecords:
        - '"dm-verify=Xu0tRlsQkukXwSqkeptKGmIaMTC30Crn2d30o_Ud9js"'

  # SES domain verification
  SESTxtRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Sub "_amazonses.${DomainName}"
      Type: TXT
      TTL: 300
      ResourceRecords:
        - '"l30+upLbh637n+iuAQwWMCXX9/Lcis+TLyXLt4UUrdo="'

  # DKIM records
  DKIMRecord1:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Sub "3khfc6s7gmqv3ep43rrrb2jxs4ksryru._domainkey.${DomainName}"
      Type: CNAME
      TTL: 300
      ResourceRecords:
        - 3khfc6s7gmqv3ep43rrrb2jxs4ksryru.dkim.amazonses.com

  DKIMRecord2:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Sub "swmtjiwan23a3x7auge3eifn3cqg2h6y._domainkey.${DomainName}"
      Type: CNAME
      TTL: 300
      ResourceRecords:
        - swmtjiwan23a3x7auge3eifn3cqg2h6y.dkim.amazonses.com

  DKIMRecord3:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !Sub "ifdcv3ufqhwbe76hzlhu2ehcjcdwvqgu._domainkey.${DomainName}"
      Type: CNAME
      TTL: 300
      ResourceRecords:
        - ifdcv3ufqhwbe76hzlhu2ehcjcdwvqgu.dkim.amazonses.com

Outputs:
  HostedZoneId:
    Value: !Ref HostedZone
    Description: Hosted zone ID (pass to site stack)
    Export:
      Name: !Sub "${AWS::StackName}-HostedZoneId"
  NameServers:
    Value: !Join [", ", !GetAtt HostedZone.NameServers]
    Description: Set these as NS records at your domain registrar
